### ISSUE TITLE
APICalls Usage

### ISSUE THREAD

**Issue by MelbourneDeveloper** [Fusioon/FusionGKeys#1]
Hi,

Sorry to bother you. I noticed that you have used the APICalls calls class from Hid.Net. I was just curious as to why you didn't use the higher level framework...

Is there anything you got stuck on? Is there anything I can do to make it easier for you moving in to future?

Christian

**Comment by Fusioon** [comment]
Hello,

Really sorry for super late reply. From what I can remember I had encountered some weird problem (some exception) which didn't occur when i used the lower level API. And at the time I really didn't thought about it much. I did revisit the code and replaced the APICalls with the higher level interfaces without any problems. So not a problem of the library but of the user. Thanks for great library.
